### ISSUE TITLE
Auto-indent seems incorrect and aggressive

### ISSUE THREAD

**Issue by Remillard** [gmlarumbe/vhdl-ts-mode#1] opened 2023-09-21 13:49 UTC
So I've been experimenting with the mode, coming from over a decade of using `vhdl-mode` so that's the basis for my observations.

I'm finding that there's something that's auto-indenting in a very weirdly aggressive way.  For example, I'm typing up the start of a file and I put in a comment line using the stutter insertion of `---` starting at column 0.  Immediately after inserting a comment, it's trying to put the cursor one indentation depth in afterwards.

Similarly, I'm between the entity block and the architecture block, and it's trying to put auto-indentation at 4.

`vhdl-mode` does not do this, so I don't feel like the `vhdl-ts-mode` should do this.

**Comment by gmlarumbe** [comment] 2023-09-21 22:31
Hi @Remillard ,

Thanks for reporting and opening the first issue! :)

I made some small changes in #2 so that comments and blank lines are indented properly outside of entities and architectures. I also added a couple of tests for these cases.

Could you check if it now works as expected?

Thanks!

**Comment by gmlarumbe** [comment] 2023-09-29 21:52
Hi @Remillard ,

After some more tests I believe the issue is fixed now. 

Feel free to report it back again in case I missed something.

Thanks!

**Closed as completed by gmlarumbe** 2023-09-29 21:52 UTC
